language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install -r requirements.txt
  - npm install
  - gulp build

script:
  - python manage.py test
