language: python
python:
  - "3.3"
  - "3.4"

before_install:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32

install:
  - pip install -r requirements.txt
  - npm install
  - gulp build

script:
  - python manage.py test
