sudo: false
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install -r requirements.txt
  - npm install

script:
  - python manage.py test
